### ISSUE TITLE
issue with last version of the code

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#56]
I try to adapt old code to new version and I have this issue for none native dataset.

(tf) tgg@gvalmu00008 training % python AttFP.py config.cfg
ERROR:root:Module 'kgcnn.utils.learning' is deprecated and will be removed in future versions. Please move to 'kgcnn.training'.
WARNING:root:Module 'kgcnn.selection' will be removed in future versions in favour of 'kgcnn.hyper'.
ERROR:root:Module 'kgcnn.utils.data' is deprecated and will be removed in future versions. Please move to 'kgcnn.data.utils'.
ERROR:kgcnn.mol.convert:Can not import OpenBabel module for conversion.
Load config file:  config.cfg
Architecture selected: GIN
My parameters
Loss RMSE
LSTM 16
DENSE 16
PROBA 0
LR start 0.01
Metal device set to: Apple M1 Max

systemMemory: 64.00 GB
maxCacheSize: 24.00 GB

2022-07-11 14:01:58.468538: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-11 14:01:58.468690: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
before True
{'model': {'name': 'GIN', 'inputs': [{'shape': [None, 41], 'name': 'node_attributes', 'dtype': 'float32', 'ragged': True}, {'shape': [None, 11], 'name': 'edge_attributes', 'dtype': 'float32', 'ragged': True}], 'input_embedding': {'node': {'input_dim': 96, 'output_dim': 100}}, 'last_mlp': {'use_bias': True, 'units': [200, 100, 1], 'activation': ['kgcnn>leaky_relu', 'kgcnn>selu', 'linear']}, 'depth': 4, 'dropout': 0.1, 'gin_args': {'units': [100, 100], 'use_bias': True, 'activation': ['relu', 'relu'], 'use_normalization': True, 'normalization_technique': 'batch'}, 'output_embedding': 'graph', 'output_mlp': {'activation': 'linear', 'units': 1}}, 'training': {'fit': {'batch_size': 32, 'epochs': 200, 'validation_freq': 1, 'verbose': 2, 'callbacks': []}, 'compile': {'optimizer': {'class_name': 'Adam', 'config': {'lr': {'class_name': 'ExponentialDecay', 'config': {'initial_learning_rate': 0.001, 'decay_steps': 1600, 'decay_rate': 0.5, 'staircase': False}}}}, 'loss': 'mean_absolute_error'}, 'cross_validation': {'class_name': 'KFold', 'config': {'n_splits': 5, 'random_state': None, 'shuffle': True}}}, 'data': {'dataset': {'class_name': 'MoleculeNetDataset', 'config': {}, 'methods': [{'set_attributes': {}}]}, 'data_unit': 'unit'}, 'info': {'postfix': '', 'kgcnn_version': '2.0.3'}}
WARNING:kgcnn.hyper.hyper:Hyperparameter {'model': ...} changed to {'model': {'config': {...}}}
INFO:kgcnn.hyper.hyper:Adding model class to 'model': {'class_name': make_model}
INFO:kgcnn.hyper.hyper:Adding 'postfix_file' to 'info' category in hyperparameter.
INFO:kgcnn.hyper.hyper:Adding 'multi_target_indices' to 'training' category in hyperparameter.
training
INFO:kgcnn.data.MoleculeNetDataset:Generating molecules and store train.sdf to disk...
[14:01:58] Explicit valence for atom # 6 N, 4, is greater than permitted
WARNING:kgcnn.mol.convert:Failed conversion for smile C1C=CC=C2C3N(=CC=CC=3)CCN2=1
[14:01:58] Explicit valence for atom # 11 O, 3, is greater than permitted
[14:01:58] Explicit valence for atom # 6 N, 4, is greater than permitted
WARNING:kgcnn.mol.convert:Failed conversion for smile C1=CC(C2C=CN(C)=CC=2)=CC=N1C
WARNING:kgcnn.mol.convert:Failed conversion for smile C12=CC=C(N(CC)CC)C=C2O=C2C=C(C=CC2=C1C1=CC=CC=C1C(O)=O)N(CC)CC
INFO:kgcnn.data.MoleculeNetDataset: ... converted molecules 466 from 466
INFO:kgcnn.data.MoleculeNetDataset: ... read molecules 0 from 466
[14:02:00] CTAB version string invalid at line 4
[14:02:01] CTAB version string invalid at line 4
[14:02:01] CTAB version string invalid at line 4
****************************************************************************************************
WARNING:kgcnn.data.MoleculeNetDataset:Property node_attributes is not set on any graph.
WARNING:kgcnn.data.MoleculeNetDataset:Can not clean property {'shape': [None, 41], 'name': 'node_attributes', 'dtype': 'float32', 'ragged': True} as it was not assigned to any graph.
WARNING:kgcnn.data.MoleculeNetDataset:Property edge_attributes is not set on any graph.
WARNING:kgcnn.data.MoleculeNetDataset:Can not clean property {'shape': [None, 11], 'name': 'edge_attributes', 'dtype': 'float32', 'ragged': True} as it was not assigned to any graph.
INFO:kgcnn.data.MoleculeNetDataset:No invalid graphs for assigned properties found.
dataset
WARNING:kgcnn.data.MoleculeNetDataset:Property node_attributes is not set on any graph.
Traceback (most recent call last):
  File "/Users/tgg/Github/tensorflow-m1-setup/gcnn_keras/training/AttFP.py", line 842, in <module>
    Xdata = dataset.tensor(inputs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/data/base.py", line 370, in tensor
    return [self._to_tensor(x, make_copy=make_copy) for x in items]
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/data/base.py", line 370, in <listcomp>
    return [self._to_tensor(x, make_copy=make_copy) for x in items]
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/data/base.py", line 362, in _to_tensor
    return ragged_tensor_from_nested_numpy(props)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/data/utils.py", line 156, in ragged_tensor_from_nested_numpy
    return tf.RaggedTensor.from_row_lengths(np.concatenate(numpy_list, axis=0),
  File "<__array_function__ internals>", line 180, in concatenate
TypeError: dispatcher for __array_function__ did not return an iterable

**Comment by PatReis** [comment]
Otherwise just send me a mail with the code and I will update it or you can send me a link with the github repo and I will make pull request.

**Comment by PatReis** [comment]
okay then you need 
```python
dataset.read_in_memory(...)
dataset.set_attributes()
```

**Comment by thegodone** [comment]
next error:

Traceback (most recent call last):
  File "/Users/tgg/Github/tensorflow-m1-setup/gcnn_keras/training/AttFP.py", line 899, in <module>
    model = make_model(**hyperparams['model']["config"])
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/utils/models.py", line 137, in update_wrapper
    return func(*args, **updated_kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/literature/GIN.py", line 93, in make_model
    n = GIN(**gin_args)([n, edi])
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/layers/conv/gin_conv.py", line 36, in __init__
    super(GIN, self).__init__(**kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/layers/base.py", line 32, in __init__
    super(GraphBaseLayer, self).__init__(**kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 332, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/generic_utils.py", line 1174, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'units')

**Comment by PatReis** [comment]
Okay so I added a `set_methods()` function to the dataset:
```python
dataset.read_in_memory(...)
dataset.set_attributes()
# For geometric models
dataset.set_methods(hyper["data"]["dataset"]["methods"])
```

**Comment by PatReis** [comment]
No you need to have for GINE:
```python
                "inputs": [{"shape": [None, 41], "name": "node_attributes", "dtype": "float32", "ragged": True},
                           {"shape": [None, 11], "name": "edge_attributes", "dtype": "float32", "ragged": True},
                           {"shape": [None, 2], "name": "edge_indices", "dtype": "int64", "ragged": True}],
```
and normal GIN:
```python
                "inputs": [{"shape": [None, 41], "name": "node_attributes", "dtype": "float32", "ragged": True},
                           {"shape": [None, 2], "name": "edge_indices", "dtype": "int64", "ragged": True}],
```

**Comment by PatReis** [comment]
just use `make_model_edge` instead of `make_model`

**Comment by PatReis** [comment]
Since it is essentially the same model I keep them in the same module, so same model name, but different make_functions.
This is for functional API. One could also just define subclasses instead of functional model definitions.
Then instead of `make_model` we could have `ModelGIN` that can be created the same way via 
```python
model = ModelGIN(**kwargs)  # Subclassed
model = make_model(**kwargs)  # Functional API
```
but we only have function API model definitions atm.

**Comment by PatReis** [comment]
So for the future I have this as model config planned:
```python
        {"model": {
            "class_name": "make_model_edge",
            "module_name": "kgcnn.literature.GIN",
            "config": {
                "name": "GIN",
                "inputs": [{"shape": [None, 41], "name": "node_attributes", "dtype": "float32", "ragged": True},
                           {"shape": [None, 11], "name": "edge_attributes", "dtype": "float32", "ragged": True},
                           {"shape": [None, 2], "name": "edge_indices", "dtype": "int64", "ragged": True}],
                "input_embedding": {"node": {"input_dim": 96, "output_dim": 64}},
                "depth": 5,
                "dropout": 0.05,
                "gin_mlp": {"units": [64, 64], "use_bias": True, "activation": ["relu", "linear"],
                            "use_normalization": True, "normalization_technique": "batch"},
                "gin_args": {},
                "last_mlp": {"use_bias": True, "units": [64, 32, 1], "activation": ["relu", "relu", "linear"]},
                "output_embedding": "graph",
                "output_mlp": {"activation": "linear", "units": 1}
            }
        }
```

**Comment by thegodone** [comment]
can you add kgcnn>selu function please in the repo ?

**Comment by thegodone** [comment]
question if I need to change the output dim I need to change both last_mlp and output_mlp last unit dimension correct ?

**Comment by thegodone** [comment]
there is something wrong with TF mac M1 

INFO:kgcnn.utils.models:Updated model kwargs:
INFO:kgcnn.utils.models:{'name': 'GIN', 'inputs': [{'shape': [None, 41], 'name': 'node_attributes', 'dtype': 'float32', 'ragged': True}, {'shape': [None, 11], 'name': 'edge_attributes', 'dtype': 'float32', 'ragged': True}, {'shape': [None, 2], 'name': 'edge_indices', 'dtype': 'int64', 'ragged': True}], 'input_embedding': {'node': {'input_dim': 96, 'output_dim': 64}, 'edge': {'input_dim': 5, 'output_dim': 64}}, 'gin_mlp': {'units': [64, 64], 'use_bias': True, 'activation': ['relu', 'relu'], 'use_normalization': True, 'normalization_technique': 'batch'}, 'gin_args': {'epsilon_learnable': False}, 'depth': 4, 'dropout': 0.05, 'verbose': 10, 'last_mlp': {'use_bias': True, 'units': [128, 64, 1], 'activation': ['kgcnn>leaky_relu', 'kgcnn>leaky_relu', 'linear']}, 'output_embedding': 'graph', 'output_to_tensor': True, 'output_mlp': {'use_bias': True, 'units': 1, 'activation': 'linear'}}
Traceback (most recent call last):
  File "/Users/tgg/Github/tensorflow-m1-setup/gcnn_keras/training/AttFP.py", line 919, in <module>
    model = make_model(**hyperparams['model']["config"])
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/utils/models.py", line 137, in update_wrapper
    return func(*args, **updated_kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.0.3-py3.9.egg/kgcnn/literature/GIN.py", line 222, in make_model_edge
    model = ks.models.Model(inputs=[node_input, edge_index_input], outputs=out)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/functional.py", line 148, in __init__
    self._init_graph_network(inputs, outputs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/functional.py", line 232, in _init_graph_network
    nodes, nodes_by_depth, layers, _ = _map_graph_network(
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/functional.py", line 998, in _map_graph_network
    raise ValueError(
ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=RaggedTensorSpec(TensorShape([None, None, 11]), tf.float32, 1, tf.int64), name='edge_attributes', description="created by layer 'edge_attributes'") at layer "optional_input_embedding_1". The following previous layers were accessed without issue: []

**Comment by PatReis** [comment]
You mean other than [tf.keras.activations.selu()](https://www.tensorflow.org/api_docs/python/tf/keras/activations/selu)

**Comment by thegodone** [comment]
Yes normal selu but i see that you did leakyrelu as internal function

**Comment by thegodone** [comment]
I am testing M1 max tf gpu

**Comment by PatReis** [comment]
I do not fully understand do you mean a 'leakyselu', because you should always be able to simply set `'activation': 'selu'` to use tensorflow's selu function.

**Comment by thegodone** [comment]
still not working ValueError: Model generation 'make_model' does not agree with hyperparameter 'make_model_edge'
I will send you an email with the code

**Comment by thegodone** [comment]
email sent I put 3 examples cases with 3 differents errors ... I did not test the others models yet.

**Comment by thegodone** [comment]
GINE is working now I fix it but not the GIN version it's always asked for 3 inputs strangely...
