### ISSUE TITLE
How to save a model

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#6]
having issue to save AttentiveFP model using callback function:

adding a callback to save best model give me an error:
filepath="Best-weights-my_model-{epoch:03d}-{loss:.4f}.hdf5"
ckp = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')

error:
Epoch 00001: val_loss improved from inf to 1.58387, saving model to Best-weights-my_model-001-3.4439.hdf5
Traceback (most recent call last):
  File "train_attentionfp_esol.py", line 149, in <module>
    validation_freq=epostep, validation_data=(xtest, ytest_), verbose=2)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 412, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1249, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1301, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1979, in save
    signatures, options)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 131, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 109, in save_model_to_hdf5
    model_metadata = saving_utils.model_metadata(model, include_optimizer)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 154, in model_metadata
    model_config['config'] = model.get_config()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 598, in get_config
    return copy.deepcopy(get_network_config(self))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1278, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
  File "/opt/conda/lib/python3.7/site-packages/kgcnn-1.0.2-py3.7.egg/kgcnn/layers/attention.py", line 471, in get_config
KeyError: 'mrecurrent_regularizer'

can we solve this ?

**Comment by thegodone** [comment]
this was solve via this commit #9049af669b591b1c9d7a1dd4e5cb02523efcb127
