### ISSUE TITLE
masks in MAT

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#86]
Very nice work on MAT implementation I still have a serie of question on the masks:

Q1: 
In the original code for the distance they use a trick 
![image](https://user-images.githubusercontent.com/1186658/192208489-16bea025-58b6-4881-9c13-4b9a2e7cef53.png)

in our code you do twice the masking will 

![image](https://user-images.githubusercontent.com/1186658/192208235-21e446bc-e32f-477a-b95b-76692daf4da3.png)

Q2: same question related to mask of  adjacency and h this is very strange ... cause there is a normalization 
I referring to this page : https://github.com/gmum/huggingmolecules/blob/7f5aacbd0c443e01bba9a2def7fdb32b0a3fa540/src/huggingmolecules/models/models_mat.py

![image](https://user-images.githubusercontent.com/1186658/192209006-37fd9a6f-ed08-4de5-951a-4425dee304dd.png)

**Comment by thegodone** [comment]
Indeed I got an error 
15/15 - 10s - loss: 0.5536 - scaled_mean_absolute_error: 1.1741 - scaled_root_mean_squared_error: 1.4774 - lr: 9.9505e-04 - 10s/epoch - 693ms/step
Epoch 4/400
Traceback (most recent call last):
  File "/Users/tgg/Github/kgcnn-ori/training/train_moleculenet.py", line 130, in <module>
    hist = model.fit(x_train, y_train,
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'RaggedValueRowIds/RaggedSplitsToSegmentIds/Repeat/boolean_mask/Reshape' defined at (most recent call last):
    File "/Users/tgg/Github/kgcnn-ori/training/train_moleculenet.py", line 130, in <module>
      hist = model.fit(x_train, y_train,
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 993, in train_step
      y_pred = self(x, training=True)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/functional.py", line 510, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/functional.py", line 667, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/kgcnn-2.1.0-py3.9.egg/kgcnn/layers/casting.py", line 139, in call
      indices_batch = tf.expand_dims(tf.cast(indices.value_rowids(), indices.values.dtype), axis=-1)
Node: 'RaggedValueRowIds/RaggedSplitsToSegmentIds/Repeat/boolean_mask/Reshape'
Input to reshape is a tensor with 4480 values, but the requested shape has 1
	 [[{{node RaggedValueRowIds/RaggedSplitsToSegmentIds/Repeat/boolean_mask/Reshape}}]] [Op:__inference_train_function_213571]

**Comment by PatReis** [comment]
I added the mask for ``exp(-x)`` and ``sofmtax(x)``. For softmax it is indeed necessary, otherwise the max would be smaller with padded values.
I tried to make the casting more stable now. Can you run again. Although I do not undestand your error.

**Comment by thegodone** [comment]
few suggestion to mimic paper:

1 . add a dropout in attention before the end product
dropout=0.1 default
![image](https://user-images.githubusercontent.com/1186658/192475921-87ef88e8-d40f-4649-9c90-fda7a928e872.png)

2. sum of lambdas is set to 1 and default are:
lambda_attention=0.3, lambda_distance=0.3, 
lambda_adjacency = 1. - lambda_attention - lambda_distance
softmax kernel 

I did not see anymore the error.

**Comment by thegodone** [comment]
I need to run the model with the original code to see final performance cause it's not clear for me... both RMAT / MAT pretrained are good in paper but not as good as other methods. and your results show very bad performance too.

**Comment by thegodone** [comment]
yes much better indeed

**Comment by thegodone** [comment]
We are good now
